[package]
name = "similar"
version = "0.2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>", "Pierre-Étienne Meunier <pe@pijul.org>"]
edition = "2018"
license = "Apache-2.0"
description = "A diff library for Rust"
repository = "https://github.com/mitsuhiko/similar"
keywords = ["diff", "difference", "patience", "compare", "changes"]
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["text"]
text = []
unicode = ["unicode-segmentation"]

[dev-dependencies]
insta = "1.5.2"

[dependencies]
unicode-segmentation = { version = "1.7.1", optional = true }
